site_name: Mahdi's Blog
site_description: I share everything I learn about technology
site_url: https://mahdijafari1.github.io/blog/
theme:
  name: material
  custom_dir: assets
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tab.link
nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Open Source: /projects/open-source/
  - Contact: contact.md
  - Blog:
     - Python: /python/
     - Django: /django/
     - FastAPI: /fastapi/ 
     - Linux: /linux/
     - Docker: /docker/